### ISSUE TITLE
ExponentialMovingAverage error

### ISSUE THREAD

**Issue by aSmallsheep** [MaybeShewill-CV/nsfw-classification-tensorflow#1]
Hello:
   when I used the test_nsfw.py to predict image with the model/nsfw_export_saved_model/1/variables/variables.index

I encountered the following problem:
W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key nsfw_cls_model/resnet_block_layer_3/block_fn_4/bn_1/beta/ExponentialMovingAverage not found in checkpoint
which means when training the saver errors,it is wrong by  saver = tf.train.Saver() to store the models

**Comment by MaybeShewill-CV** [comment]
@aSmallsheep Plese details the command you use and your local environment:)

**Comment by aSmallsheep** [comment]
I use the command:
 python test_nsfw.py --weights_path model/nsfw_export_saved_model/1/variable
s/variables --image_path data/test_data/hentai_16814.jpg

The problems are:
2019-03-20 15:43:14.057068: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key nsfw_cls_model/resnet_block_layer_2/block_fn_1/conv_pad_1/conv/W/ExponentialMovingAverage not found in checkpoint
2019-03-20 15:43:14.057167: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key nsfw_cls_model/resnet_block_layer_2/block_fn_2/bn_1/gamma/ExponentialMovingAverage not found in checkpoint
2019-03-20 15:43:14.057895: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key nsfw_cls_model/resnet_block_layer_2/block_fn_2/bn_1/beta/ExponentialMovingAverage not found in checkpoint

**Comment by MaybeShewill-CV** [comment]
@aSmallsheep Please check README file carefully and correct your command:)

**Comment by aSmallsheep** [comment]
I have moved the test_nsfw.py and other .py files in the REPO_ROOT_DIR
then python test_nsfw.py --weights_path model/nsfw_export_saved_model/1/variable
s/variables --image_path data/test_data/hentai_16814.jpg
Is the --weights_path wrong?

**Comment by MaybeShewill-CV** [comment]
@aSmallsheep You may read it and test it yourself 
![Screenshot from 2019-03-20 16-28-39](https://user-images.githubusercontent.com/15725187/54669853-526d0a00-4b2d-11e9-8528-ce0881f087b6.png)

**Comment by aSmallsheep** [comment]
I　have  tried, unlucky，I couldn't downloaded the pretrained weights_file. other urls？

**Comment by MaybeShewill-CV** [comment]
@aSmallsheep Sorry for that. If you've got training samples you may train your own model. Or you may google how to save tensorflow model from tensorflow saved model:)

**Comment by aSmallsheep** [comment]
I know how to fix it.Thanks a lot.
